apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-backend-user
  template:
    metadata:
      labels:
        app: k8s-backend-user
    spec:
      containers:
        - name: backend-user
          image: backend-user:latest
          imagePullPolicy: Never
          readinessProbe:
            httpGet:
              port: 8080
              path: /user/actuator/health/readiness
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 8080
              path: /user/actuator/health/liveness
            initialDelaySeconds: 30
            periodSeconds: 10
